#!/usr/bin/env bash
set -euo pipefail

usage() {
  printf '%s\n' 'Usage: compose-topology.sh --baseline FILE --topology FILE --output FILE'
}

baseline=''
topology=''
output=''

while (($#)); do
  case "$1" in
    --baseline) baseline=$2; shift 2 ;;
    --topology) topology=$2; shift 2 ;;
    --output) output=$2; shift 2 ;;
    *) usage >&2; exit 2 ;;
  esac
done

[[ -n "$baseline" && -f "$baseline" ]] || { printf 'baseline not found: %s\n' "$baseline" >&2; exit 2; }
[[ -n "$topology" && -f "$topology" ]] || { printf 'topology overlay not found: %s\n' "$topology" >&2; exit 2; }
[[ -n "$output" ]] || { usage >&2; exit 2; }
command -v yq >/dev/null 2>&1 || { printf '%s\n' 'yq is required' >&2; exit 2; }

environment=$(yq -r '.environment // ""' "$topology")
[[ -n "$environment" ]] || { printf '%s\n' 'topology environment is required' >&2; exit 1; }

missing_overrides=$(BASELINE="$baseline" TOPOLOGY="$topology" ENVIRONMENT="$environment" yq -n -r '
  load(strenv(BASELINE)) as $baseline |
  load(strenv(TOPOLOGY)) as $topology |
  ($baseline.clusters[strenv(ENVIRONMENT)].workloadCells | keys) -
  ($topology.workloadCellOverrides | keys) | join(",")
')
unknown_overrides=$(BASELINE="$baseline" TOPOLOGY="$topology" ENVIRONMENT="$environment" yq -n -r '
  load(strenv(BASELINE)) as $baseline |
  load(strenv(TOPOLOGY)) as $topology |
  ($topology.workloadCellOverrides | keys) -
  ($baseline.clusters[strenv(ENVIRONMENT)].workloadCells | keys) | join(",")
')
[[ -z "$missing_overrides" ]] || { printf 'baseline cells missing topology overrides: %s\n' "$missing_overrides" >&2; exit 1; }
[[ -z "$unknown_overrides" ]] || { printf 'topology overrides reference unknown baseline cells: %s\n' "$unknown_overrides" >&2; exit 1; }

output_dir=$(dirname -- "$output")
mkdir -p "$output_dir"
temporary=$(mktemp "$output_dir/.topology.XXXXXX")
trap 'rm -f "$temporary"' EXIT

printf '%s\n' '# Generated by scripts/compose-topology.sh; edit the baseline or topology overlay.' > "$temporary"
BASELINE="$baseline" TOPOLOGY="$topology" ENVIRONMENT="$environment" yq -n -o=yaml '
  load(strenv(BASELINE)) as $baseline |
  load(strenv(TOPOLOGY)) as $topology |
  {
    "schemaVersion": "topology.artemis.apache.org/v1",
    "environment": $topology.environment,
    "clusterName": $topology.clusterName,
    "platformNamespace": $topology.platformNamespace,
    "workloadCells": (
      $baseline.clusters[strenv(ENVIRONMENT)].workloadCells
      | to_entries
      | map(
          . as $cell |
          {"workloadCellName": $cell.key} *
          $cell.value *
          $topology.workloadCellOverrides[$cell.key]
        )
    )
  }
' >> "$temporary"

mv "$temporary" "$output"
trap - EXIT
