#!/usr/bin/env python3
"""Create review candidates from a legacy Chef ActiveMQ environment JSON file.

The importer is intentionally not a direct deployment tool. It writes one
workload-values candidate per selected legacy broker and a redacted disposition
report. Secret-bearing and intentionally retired settings never enter the
candidate files.
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import html
import json
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCHEMA_VERSION = "chef-import.artemis.apache.org/report/v1"
POLICY_SCHEMA_VERSION = "chef-import-policy.artemis.apache.org/v1"
SUPPORTED_PROTOCOLS = ("OPENWIRE", "AMQP", "STOMP", "MQTT")
ROLE_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
DESTINATION_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]*$")
SENSITIVE_KEY_PATTERN = re.compile(
    r"password|passwd|secret|token|credential|private.?key", re.IGNORECASE
)


class ImportFailure(Exception):
    """A user-correctable source, policy, or command-line error."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Translate Chef ActiveMQ environment JSON into review-only Artemis "
            "workload values candidates and a redacted migration report."
        )
    )
    parser.add_argument("--input", required=True, type=Path, help="Chef environment JSON")
    parser.add_argument(
        "--output-dir", required=True, type=Path, help="new or empty output directory"
    )
    parser.add_argument(
        "--environment",
        help="environment label for the report (defaults to Chef name or input stem)",
    )
    parser.add_argument(
        "--broker", action="append", default=[], help="legacy broker key to convert; repeatable"
    )
    parser.add_argument(
        "--activemq-path",
        help="dot-separated path to the ActiveMQ object when auto-discovery is ambiguous",
    )
    parser.add_argument("--policy", type=Path, help="optional per-environment import policy JSON")
    parser.add_argument(
        "--ssl-secret-name",
        default="",
        help="externally materialized server TLS Secret reference for TLS acceptors",
    )
    parser.add_argument(
        "--trust-secret-name",
        default="",
        help="optional externally materialized client CA Secret reference",
    )
    parser.add_argument(
        "--jaas-secret-name",
        default="",
        help="optional externally materialized JAAS Secret; must end in -jaas-config",
    )
    parser.add_argument(
        "--authenticated-broker",
        action="append",
        default=[],
        help=(
            "legacy broker that maps to a future authenticated external "
            "Workload Cell; repeatable"
        ),
    )
    parser.add_argument(
        "--keep-role",
        action="append",
        default=[],
        help="retain a role otherwise removed by policy (for example guests); repeatable",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite files generated by a prior run in a non-empty output directory",
    )
    return parser.parse_args()


def load_json(path: Path, label: str) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except FileNotFoundError as error:
        raise ImportFailure(f"{label} not found: {path}") from error
    except json.JSONDecodeError as error:
        raise ImportFailure(
            f"{label} is not valid JSON at line {error.lineno}, column {error.colno}: {path}"
        ) from error


def object_at_path(document: Any, dotted_path: str) -> dict[str, Any]:
    current = document
    for component in dotted_path.split("."):
        if not isinstance(current, dict) or component not in current:
            raise ImportFailure(f"ActiveMQ path does not exist: {dotted_path}")
        current = current[component]
    if not isinstance(current, dict):
        raise ImportFailure(f"ActiveMQ path is not an object: {dotted_path}")
    return current


def discover_activemq(document: Any, explicit_path: str | None) -> tuple[dict[str, Any], str]:
    if explicit_path:
        return object_at_path(document, explicit_path), explicit_path

    matches: list[tuple[str, dict[str, Any]]] = []

    def visit(value: Any, path: str) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                child_path = f"{path}.{key}" if path else key
                if key == "activemq" and isinstance(child, dict) and "brokers" in child:
                    matches.append((child_path, child))
                visit(child, child_path)
        elif isinstance(value, list):
            for index, child in enumerate(value):
                visit(child, f"{path}[{index}]")

    visit(document, "")
    if not matches:
        raise ImportFailure(
            "no ActiveMQ object containing brokers was found; pass --activemq-path if it uses another name"
        )
    if len(matches) > 1:
        paths = ", ".join(path for path, _ in matches)
        raise ImportFailure(f"multiple ActiveMQ objects found ({paths}); pass --activemq-path")
    path, value = matches[0]
    return value, path


def validate_secret_name(value: str, label: str, jaas: bool = False) -> None:
    if not value:
        return
    if len(value) > 253 or not re.fullmatch(r"[a-z0-9]([-a-z0-9.]*[a-z0-9])?", value):
        raise ImportFailure(f"{label} is not a valid Kubernetes Secret name: {value}")
    if jaas and not value.endswith("-jaas-config"):
        raise ImportFailure(f"{label} must end in -jaas-config")


def validate_string_list(value: Any, path: str) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ImportFailure(f"policy field {path} must be an array of strings")
    return value


def load_policy(path: Path | None) -> dict[str, Any]:
    if path is None:
        return {
            "schemaVersion": POLICY_SCHEMA_VERSION,
            "defaults": {"includeDlqDestinations": False, "dropRoles": ["guests"]},
            "brokers": {},
        }
    policy = load_json(path, "policy")
    if not isinstance(policy, dict):
        raise ImportFailure("policy root must be an object")
    allowed_root = {"schemaVersion", "defaults", "brokers"}
    unknown_root = sorted(set(policy) - allowed_root)
    if unknown_root:
        raise ImportFailure(f"unknown policy root fields: {', '.join(unknown_root)}")
    if policy.get("schemaVersion") != POLICY_SCHEMA_VERSION:
        raise ImportFailure(f"policy schemaVersion must be {POLICY_SCHEMA_VERSION}")
    defaults = policy.setdefault("defaults", {})
    brokers = policy.setdefault("brokers", {})
    if not isinstance(defaults, dict) or not isinstance(brokers, dict):
        raise ImportFailure("policy defaults and brokers must be objects")
    validate_policy_block(defaults, "defaults")
    for broker_name, block in brokers.items():
        if not isinstance(block, dict):
            raise ImportFailure(f"policy brokers.{broker_name} must be an object")
        validate_policy_block(block, f"brokers.{broker_name}")
    defaults.setdefault("includeDlqDestinations", False)
    defaults.setdefault("dropRoles", ["guests"])
    return policy


def validate_policy_block(block: dict[str, Any], path: str) -> None:
    allowed = {
        "includeDlqDestinations",
        "dropRoles",
        "acceptorAllowlist",
        "excludeAcceptors",
        "destinationAllowlist",
        "excludeDestinations",
        "authorizationAllowlist",
        "excludeAuthorizationMatches",
    }
    unknown = sorted(set(block) - allowed)
    if unknown:
        raise ImportFailure(f"unknown policy fields under {path}: {', '.join(unknown)}")
    if "includeDlqDestinations" in block and not isinstance(
        block["includeDlqDestinations"], bool
    ):
        raise ImportFailure(f"policy field {path}.includeDlqDestinations must be boolean")
    for key in allowed - {"includeDlqDestinations"}:
        if key in block:
            validate_string_list(block[key], f"{path}.{key}")


def merged_policy(policy: dict[str, Any], broker_name: str, keep_roles: list[str]) -> dict[str, Any]:
    defaults = policy["defaults"]
    broker = policy["brokers"].get(broker_name, {})
    result: dict[str, Any] = {}
    for key in (
        "acceptorAllowlist",
        "excludeAcceptors",
        "destinationAllowlist",
        "excludeDestinations",
        "authorizationAllowlist",
        "excludeAuthorizationMatches",
    ):
        result[key] = list(defaults.get(key, [])) + list(broker.get(key, []))
    result["includeDlqDestinations"] = broker.get(
        "includeDlqDestinations", defaults.get("includeDlqDestinations", False)
    )
    dropped = set(defaults.get("dropRoles", [])) | set(broker.get("dropRoles", []))
    dropped -= set(keep_roles)
    result["dropRoles"] = sorted(dropped)
    return result


def selected_by_policy(identifier: str, allow: list[str], deny: list[str]) -> tuple[bool, str]:
    if allow and not any(fnmatch.fnmatchcase(identifier, pattern) for pattern in allow):
        return False, "not selected by the policy allowlist"
    if any(fnmatch.fnmatchcase(identifier, pattern) for pattern in deny):
        return False, "excluded by the policy"
    return True, ""


def slug(value: str, maximum: int = 63) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    if not normalized or not normalized[0].isalpha():
        normalized = f"item-{normalized}".rstrip("-")
    normalized = normalized[:maximum].rstrip("-")
    return normalized or "item"


def unique_key(value: str, used: set[str], maximum: int = 63) -> str:
    base = slug(value, maximum)
    candidate = base
    if candidate in used:
        suffix = hashlib.sha256(value.encode("utf-8")).hexdigest()[:8]
        candidate = f"{base[: maximum - 9].rstrip('-')}-{suffix}"
    counter = 2
    while candidate in used:
        suffix = f"-{counter}"
        candidate = f"{base[: maximum - len(suffix)].rstrip('-')}{suffix}"
        counter += 1
    used.add(candidate)
    return candidate


def to_int(value: Any, path: str, minimum: int = 1) -> int:
    try:
        converted = int(str(value))
    except (TypeError, ValueError) as error:
        raise ImportFailure(f"{path} must be an integer; got {type(value).__name__}") from error
    if converted < minimum:
        raise ImportFailure(f"{path} must be at least {minimum}; got {converted}")
    return converted


def protocol_for_transport(fields: list[Any]) -> str | None:
    label = " ".join(str(value).lower() for value in fields[:2])
    if "openwire" in label or re.search(r"(^|\s)ssl($|\s)", label):
        return "OPENWIRE"
    if "amqp" in label:
        return "AMQP"
    if "stomp" in label or "websocket" in label or re.search(r"(^|\s)ws($|\s)", label):
        return "STOMP"
    if "mqtt" in label:
        return "MQTT"
    return None


def classic_match_to_artemis(value: str) -> str:
    if value == ">":
        return "#"
    return value.replace(".>", ".#")


def parse_roles(value: Any, dropped: set[str], report_drop: callable) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        raw_roles = [str(item).strip() for item in value]
    else:
        raw_roles = [item.strip() for item in str(value).split(",")]
    roles: list[str] = []
    for role in raw_roles:
        if not role:
            continue
        if role in dropped:
            report_drop(role)
            continue
        if not ROLE_PATTERN.fullmatch(role):
            report_drop(role, invalid=True)
            continue
        if role not in roles:
            roles.append(role)
    return sorted(roles)


def item(
    broker: str,
    source_path: str,
    disposition: str,
    reason: str,
    *,
    identifier: str | None = None,
    target_path: str | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "broker": broker,
        "sourcePath": source_path,
        "disposition": disposition,
        "reason": reason,
    }
    if identifier is not None:
        result["identifier"] = identifier
    if target_path is not None:
        result["targetPath"] = target_path
    return result


def sensitive_paths(document: Any) -> list[str]:
    found: list[str] = []

    def visit(value: Any, path: str) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                child_path = f"{path}.{key}" if path else key
                if SENSITIVE_KEY_PATTERN.search(key):
                    found.append(child_path)
                    continue
                visit(child, child_path)
        elif isinstance(value, list):
            for index, child in enumerate(value):
                visit(child, f"{path}[{index}]")

    visit(document, "")
    return sorted(set(found))


def transform_broker(
    broker_name: str,
    broker: dict[str, Any],
    source_base: str,
    policy: dict[str, Any],
    args: argparse.Namespace,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    report_items: list[dict[str, Any]] = []
    candidate: dict[str, Any] = {}
    acceptors: dict[str, Any] = {}
    destinations: dict[str, Any] = {}
    authorization_rules: dict[str, Any] = {}
    used_acceptor_keys: set[str] = set()
    used_destination_keys: set[str] = set()
    used_rule_keys: set[str] = set()
    used_ports: dict[int, str] = {}
    authenticated = broker_name in args.authenticated_broker

    transports = broker.get("transports", [])
    if transports is None:
        transports = []
    if not isinstance(transports, list):
        raise ImportFailure(f"{source_base}.transports must be an array")
    for index, transport in enumerate(transports):
        source_path = f"{source_base}.transports[{index}]"
        if not isinstance(transport, list) or len(transport) < 5:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    "transport must be a positional array with at least name, type, bind, port, and connection limit",
                )
            )
            continue
        source_name = str(transport[0])
        selected, reason = selected_by_policy(
            source_name, policy["acceptorAllowlist"], policy["excludeAcceptors"]
        )
        if not selected:
            report_items.append(
                item(broker_name, source_path, "policy-excluded", reason, identifier=source_name)
            )
            continue
        protocol = protocol_for_transport(transport)
        if protocol not in SUPPORTED_PROTOCOLS:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    "transport protocol could not be mapped to OPENWIRE, AMQP, STOMP, or MQTT",
                    identifier=source_name,
                )
            )
            continue
        try:
            port = to_int(transport[3], f"{source_path}[3]")
            connections = to_int(transport[4], f"{source_path}[4]")
        except ImportFailure as error:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    str(error),
                    identifier=source_name,
                )
            )
            continue
        if port > 65535:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    f"port {port} is outside the Kubernetes Service range",
                    identifier=source_name,
                )
            )
            continue
        transport_tail = html.unescape("&".join(str(value) for value in transport[5:]))
        query_parameters = [
            token.strip()
            for token in re.split(r"[?&]", transport_tail)
            if "=" in token
        ]
        tls_enabled = "ssl" in " ".join(str(value).lower() for value in transport[:2])
        source_need_client_auth = any(
            parameter.lower() == "needclientauth=true" for parameter in query_parameters
        )
        need_client_auth = source_need_client_auth and authenticated
        if source_need_client_auth and not authenticated:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "retired",
                    (
                        "internal broker client authentication was not carried forward; "
                        "access is owned by approved CIDR policy"
                    ),
                    identifier=source_name,
                )
            )
        if tls_enabled and not args.ssl_secret_name:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "manual",
                    "TLS listener was not generated because --ssl-secret-name was not supplied",
                    identifier=source_name,
                )
            )
            continue
        if port in used_ports:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    f"port {port} duplicates transport {used_ports[port]}; the chart requires unique enabled ports",
                    identifier=source_name,
                )
            )
            continue
        used_ports[port] = source_name
        key_seed = "artemis" if protocol == "OPENWIRE" and port == 61616 else source_name
        acceptor_key = unique_key(key_seed, used_acceptor_keys, maximum=32)
        protocols = "CORE,OPENWIRE" if protocol == "OPENWIRE" and port == 61616 else protocol
        extra_params: dict[str, str] = {}
        transport_label = " ".join(str(value).lower() for value in transport[:2])
        if "websocket" in transport_label or re.search(r"(^|\s)ws($|\s)", transport_label):
            extra_params["httpEnabled"] = "true"
        acceptors[acceptor_key] = {
            "enabled": True,
            "port": port,
            "protocols": protocols,
            "connectionsAllowed": connections,
            "bindToAllInterfaces": True,
            "supportAdvisory": protocol == "OPENWIRE",
            "suppressInternalManagementObjects": protocol != "OPENWIRE",
            "sslEnabled": tls_enabled,
            "needClientAuth": need_client_auth,
            "sslSecret": args.ssl_secret_name if tls_enabled else "",
            "trustSecret": args.trust_secret_name if tls_enabled else "",
            "extraParams": extra_params,
        }
        report_items.append(
            item(
                broker_name,
                source_path,
                "candidate-review",
                "listener shape was translated; verify that clients still use this protocol and port before retaining it",
                identifier=source_name,
                target_path=f"acceptors.{acceptor_key}",
            )
        )
        if len(transport) > 5:
            report_items.append(
                item(
                    broker_name,
                    f"{source_path}[5:]",
                    "manual",
                    "legacy positional frame, inactivity, and delay tuning was not copied without a named semantic mapping and load-test evidence",
                    identifier=source_name,
                )
            )
        bind_address = str(transport[2])
        if bind_address not in ("0.0.0.0", "::", ""):
            report_items.append(
                item(
                    broker_name,
                    f"{source_path}[2]",
                    "manual",
                    "legacy bind address was replaced by the chart-owned all-interface bind; exposure remains Service and NetworkPolicy owned",
                    identifier=source_name,
                )
            )
        remaining_query = [
            parameter
            for parameter in query_parameters
            if parameter.lower() != "needclientauth=true"
        ]
        if remaining_query:
            report_items.append(
                item(
                    broker_name,
                    f"{source_path}[8:]",
                    "manual",
                    "unmapped transport query parameters require an explicit Artemis semantic mapping",
                    identifier=source_name,
                )
            )

    queues = broker.get("queues", [])
    if queues is None:
        queues = []
    if not isinstance(queues, list):
        raise ImportFailure(f"{source_base}.queues must be an array")
    queue_names: set[str] = set()
    for index, raw_name in enumerate(queues):
        source_path = f"{source_base}.queues[{index}]"
        if not isinstance(raw_name, str) or not DESTINATION_PATTERN.fullmatch(raw_name):
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    "queue name is not valid for the typed Artemis destination interface",
                )
            )
            continue
        if raw_name in queue_names:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "default-excluded",
                    "duplicate queue declaration was collapsed",
                    identifier=raw_name,
                )
            )
            continue
        queue_names.add(raw_name)
        selected, reason = selected_by_policy(
            raw_name, policy["destinationAllowlist"], policy["excludeDestinations"]
        )
        if not selected:
            report_items.append(
                item(broker_name, source_path, "policy-excluded", reason, identifier=raw_name)
            )
            continue
        if raw_name.startswith("DLQ.") and not policy["includeDlqDestinations"]:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "default-excluded",
                    "DLQ-prefixed queue is replaced by the chart's automatic per-source DLQ policy",
                    identifier=raw_name,
                )
            )
            continue
        destination_key = unique_key(raw_name, used_destination_keys)
        destinations[destination_key] = {
            "address": raw_name,
            "routingTypes": ["ANYCAST"],
            "queues": [
                {
                    "name": raw_name,
                    "routingType": "ANYCAST",
                    "durable": True,
                    "maxConsumers": -1,
                    "purgeOnNoConsumers": False,
                }
            ],
        }
        report_items.append(
            item(
                broker_name,
                source_path,
                "candidate-review",
                "queue was translated as a durable ANYCAST address and queue; confirm ownership and current use",
                identifier=raw_name,
                target_path=f"destinations.{destination_key}",
            )
        )

    ssl = broker.get("ssl", {})
    if ssl is None:
        ssl = {}
    if not isinstance(ssl, dict):
        raise ImportFailure(f"{source_base}.ssl must be an object")
    entries_in_ssl = "authorizationEntries" in ssl
    entries = ssl.get("authorizationEntries", broker.get("authorizationEntries", []))
    entries_base = (
        f"{source_base}.ssl.authorizationEntries"
        if entries_in_ssl
        else f"{source_base}.authorizationEntries"
    )
    if entries is None:
        entries = []
    if not isinstance(entries, list):
        raise ImportFailure(f"{source_base}.ssl.authorizationEntries must be an array")
    dropped_roles = set(policy["dropRoles"])
    grouped_rules: dict[str, dict[str, set[str]]] = {}
    grouped_sources: dict[str, list[str]] = {}
    grouped_kinds: dict[str, set[str]] = {}
    exact_topics: dict[str, str] = {}

    for index, entry in enumerate(entries):
        source_path = f"{entries_base}[{index}]"
        if not isinstance(entry, list) or len(entry) < 5:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    "authorization entry must contain type, match, read roles, write roles, and admin roles",
                )
            )
            continue
        kind = str(entry[0]).lower()
        classic_match = str(entry[1])
        if kind not in ("queue", "topic"):
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    f"authorization type {kind!r} is not queue or topic",
                    identifier=classic_match,
                )
            )
            continue
        selected, reason = selected_by_policy(
            classic_match,
            policy["authorizationAllowlist"],
            policy["excludeAuthorizationMatches"],
        )
        if not selected:
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "policy-excluded",
                    reason,
                    identifier=classic_match,
                )
            )
            continue
        artemis_match = classic_match_to_artemis(classic_match)
        if not re.fullmatch(r"[A-Za-z0-9#*][A-Za-z0-9#*._:/-]*", artemis_match):
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "unsupported",
                    "authorization match is not valid for the typed Artemis rule interface",
                    identifier=classic_match,
                )
            )
            continue

        def report_role_drop(role: str, invalid: bool = False) -> None:
            reason_text = (
                "role name is invalid for the typed Artemis interface"
                if invalid
                else "role was removed by the import policy instead of carrying forward broad legacy access"
            )
            report_items.append(
                item(
                    broker_name,
                    source_path,
                    "default-excluded" if not invalid else "unsupported",
                    reason_text,
                    identifier=None if invalid else role,
                )
            )

        read_roles = parse_roles(entry[2], dropped_roles, report_role_drop)
        write_roles = parse_roles(entry[3], dropped_roles, report_role_drop)
        admin_roles = parse_roles(entry[4], dropped_roles, report_role_drop)
        permissions = grouped_rules.setdefault(artemis_match, {})
        for operation, roles in (
            ("consume", read_roles),
            ("browse", read_roles),
            ("send", write_roles),
        ):
            permissions.setdefault(operation, set()).update(roles)
        grouped_sources.setdefault(artemis_match, []).append(source_path)
        grouped_kinds.setdefault(artemis_match, set()).add(kind)
        if admin_roles:
            report_items.append(
                item(
                    broker_name,
                    f"{source_path}[4]",
                    "manual",
                    "Classic admin roles were not granted create, delete, or manage operations because destinations are pre-created; approve exact operational grants separately",
                    identifier=classic_match,
                )
            )
        if kind == "topic" and not any(marker in artemis_match for marker in ("#", "*")):
            exact_topics.setdefault(artemis_match, source_path)

    for artemis_match in sorted(grouped_rules):
        permissions = {
            operation: sorted(roles)
            for operation, roles in grouped_rules[artemis_match].items()
            if roles
        }
        if not permissions:
            report_items.append(
                item(
                    broker_name,
                    grouped_sources[artemis_match][0],
                    "default-excluded",
                    "authorization rule has no roles after policy filtering",
                    identifier=artemis_match,
                )
            )
            continue
        rule_key = unique_key(
            f"{'-'.join(sorted(grouped_kinds[artemis_match]))}-{artemis_match}", used_rule_keys
        )
        if authenticated:
            authorization_rules[rule_key] = {
                "match": artemis_match,
                "permissions": permissions,
            }
        wildcard_note = " Wildcard scope requires an explicit least-privilege review." if any(
            marker in artemis_match for marker in ("#", "*")
        ) else ""
        report_items.append(
            item(
                broker_name,
                grouped_sources[artemis_match][0],
                "candidate-review" if authenticated else "retired",
                (
                    "Classic read/write roles were translated to consume+browse/send."
                    + wildcard_note
                    if authenticated
                    else (
                        "internal broker authorization was not carried forward; "
                        "access is owned by approved CIDR policy"
                    )
                ),
                identifier=artemis_match,
                target_path=(f"authorization.rules.{rule_key}" if authenticated else None),
            )
        )

    existing_addresses = {entry["address"] for entry in destinations.values()}
    for topic_name, source_path in sorted(exact_topics.items()):
        if topic_name in existing_addresses:
            continue
        selected, reason = selected_by_policy(
            topic_name, policy["destinationAllowlist"], policy["excludeDestinations"]
        )
        if not selected:
            report_items.append(
                item(broker_name, source_path, "policy-excluded", reason, identifier=topic_name)
            )
            continue
        if not DESTINATION_PATTERN.fullmatch(topic_name):
            continue
        destination_key = unique_key(topic_name, used_destination_keys)
        destinations[destination_key] = {
            "address": topic_name,
            "routingTypes": ["MULTICAST"],
            "queues": [],
        }
        report_items.append(
            item(
                broker_name,
                source_path,
                "candidate-review",
                "exact topic authorization was translated into a MULTICAST address; confirm the topic still has producers or subscribers",
                identifier=topic_name,
                target_path=f"destinations.{destination_key}",
            )
        )

    if authenticated:
        # Helm deep-merges the chart's standard plaintext client acceptors.
        # External candidates must turn off any default listener that was not
        # replaced by an explicitly imported mTLS listener. The fixed artemis
        # acceptor remains for operator-managed CORE peer traffic.
        for default_acceptor in ("amqp", "stomp", "mqtt", "websocket"):
            acceptors.setdefault(default_acceptor, {"enabled": False})

    if acceptors:
        candidate["acceptors"] = acceptors
    if authenticated:
        candidate["authentication"] = {
            "jaasSecretName": args.jaas_secret_name,
        }
        report_items.append(
            item(
                broker_name,
                f"{source_base}.ssl",
                "candidate-review",
                "only the externally materialized JAAS Secret reference was emitted; users, DNs, groups, and credentials were not copied",
                target_path="authentication.jaasSecretName",
            )
        )
    candidate["destinations"] = destinations
    candidate["authorization"] = {"rules": authorization_rules if authenticated else {}}

    for field, reason in (
        ("jmx", "remote JMX/RMI is intentionally replaced by scoped Hawtio/Jolokia access"),
        ("jettysettings", "legacy Jetty bind/listen configuration is operator owned in the new deployment"),
    ):
        if field in broker:
            report_items.append(item(broker_name, f"{source_base}.{field}", "retired", reason))
    database_fields = sorted(
        field
        for field in broker
        if field.lower().startswith("db") or field in ("lockDuration", "lockRenewInterval")
    )
    if database_fields:
        report_items.append(
            item(
                broker_name,
                f"{source_base}.[database-store]",
                "retired",
                "Classic JDBC store and lock settings are replaced by replicated Artemis file journals and ZooKeeper activation locking",
            )
        )
    for field in ("truststore", "keystore"):
        if field in broker or field in ssl:
            owner_path = source_base if field in broker else f"{source_base}.ssl"
            report_items.append(
                item(
                    broker_name,
                    f"{owner_path}.{field}",
                    "manual",
                    "legacy file paths and certificate aliases were not copied; security owners must build and rotate approved Kubernetes TLS/trust Secrets",
                )
            )
    for field in ("dnusers", "groups", "users"):
        value = ssl.get(field)
        if value:
            count = len(value) if isinstance(value, list) else 1
            report_items.append(
                item(
                    broker_name,
                    f"{source_base}.ssl.{field}",
                    "manual",
                    f"{count} legacy identity entries were detected but not emitted; reconcile them into an externally materialized JAAS Secret",
                )
            )

    known_ssl_fields = {
        "authorizationEntries",
        "truststore",
        "keystore",
        "dnusers",
        "groups",
        "users",
    }
    for field in sorted(set(ssl) - known_ssl_fields):
        report_items.append(
            item(
                broker_name,
                f"{source_base}.ssl.{field}",
                "manual",
                "unrecognized legacy SSL/security field was not copied; map it through the approved TLS or JAAS ownership boundary",
            )
        )

    known_broker_fields = {
        "transports",
        "queues",
        "ssl",
        "authorizationEntries",
        "jmx",
        "jettysettings",
        "truststore",
        "keystore",
        "lockDuration",
        "lockRenewInterval",
        "prefetchSize",
        "nioMinPoolSize",
        "nioMaxPoolSize",
    }
    known_broker_fields.update(field for field in broker if field.lower().startswith("db"))
    for field in sorted(set(broker) - known_broker_fields):
        report_items.append(
            item(
                broker_name,
                f"{source_base}.{field}",
                "manual",
                "unrecognized legacy broker field was not copied; determine whether it has a current Artemis requirement",
            )
        )
    for field in ("prefetchSize", "nioMinPoolSize", "nioMaxPoolSize"):
        if field in broker:
            report_items.append(
                item(
                    broker_name,
                    f"{source_base}.{field}",
                    "manual",
                    "legacy broker/runtime tuning was not copied without workload evidence and an Artemis-specific load test",
                )
            )

    return candidate, report_items


def yaml_scalar(value: Any) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def yaml_key(value: str) -> str:
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", value):
        return value
    return json.dumps(value, ensure_ascii=False)


def yaml_lines(value: Any, indent: int = 0) -> list[str]:
    prefix = " " * indent
    if isinstance(value, dict):
        if not value:
            return [f"{prefix}{{}}"]
        lines: list[str] = []
        for key, child in value.items():
            rendered_key = yaml_key(str(key))
            if isinstance(child, dict) and not child:
                lines.append(f"{prefix}{rendered_key}: {{}}")
            elif isinstance(child, list) and not child:
                lines.append(f"{prefix}{rendered_key}: []")
            elif isinstance(child, (dict, list)):
                lines.append(f"{prefix}{rendered_key}:")
                lines.extend(yaml_lines(child, indent + 2))
            else:
                lines.append(f"{prefix}{rendered_key}: {yaml_scalar(child)}")
        return lines
    if isinstance(value, list):
        if not value:
            return [f"{prefix}[]"]
        lines = []
        for child in value:
            if isinstance(child, dict) and child:
                first_key = next(iter(child))
                first_value = child[first_key]
                if not isinstance(first_value, (dict, list)):
                    lines.append(
                        f"{prefix}- {yaml_key(str(first_key))}: {yaml_scalar(first_value)}"
                    )
                    remainder = dict(list(child.items())[1:])
                    if remainder:
                        lines.extend(yaml_lines(remainder, indent + 2))
                else:
                    lines.append(f"{prefix}-")
                    lines.extend(yaml_lines(child, indent + 2))
            elif isinstance(child, (dict, list)):
                lines.append(f"{prefix}-")
                lines.extend(yaml_lines(child, indent + 2))
            else:
                lines.append(f"{prefix}- {yaml_scalar(child)}")
        return lines
    return [f"{prefix}{yaml_scalar(value)}"]


def candidate_yaml(candidate: dict[str, Any], report_name: str) -> str:
    header = [
        "# GENERATED REVIEW CANDIDATE — DO NOT APPLY DIRECTLY.",
        f"# Resolve every review/manual/unsupported item in {report_name}, then copy",
        "# only the approved entries into the owning Workload Cell values file.",
    ]
    return "\n".join(header + yaml_lines(candidate)) + "\n"


def markdown_report(report: dict[str, Any]) -> str:
    lines = [
        "# Chef ActiveMQ import review",
        "",
        f"Environment: `{report['environment']}`  ",
        f"Source SHA-256: `{report['sourceSha256']}`",
        "",
        "No password, token, certificate subject, certificate alias, private key, or Secret value is emitted. Candidate files are review artifacts, not deployment inputs.",
        "",
        "| Broker | Candidate | Candidate review | Manual | Retired | Excluded | Unsupported |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for broker_name, broker_report in report["brokers"].items():
        counts = broker_report["counts"]
        excluded = counts.get("default-excluded", 0) + counts.get("policy-excluded", 0)
        lines.append(
            f"| `{broker_name}` | `{broker_report['candidateFile']}` | "
            f"{counts.get('candidate-review', 0)} | {counts.get('manual', 0)} | "
            f"{counts.get('retired', 0)} | {excluded} | {counts.get('unsupported', 0)} |"
        )
    lines.extend(
        [
            "",
            "## Required review",
            "",
            "- Confirm current client use for every listener, destination, wildcard, and role; the Chef file proves declaration, not liveness.",
            "- Reconcile identities and certificates outside Git, using only approved Kubernetes Secret references in values.",
            "- Keep JDBC, remote JMX/RMI, and legacy Jetty settings retired unless a new, reviewed Artemis requirement proves otherwise.",
            "- Run chart and topology validation after approved entries are copied into a workload values file.",
            "",
            f"See `{report['jsonReportFile']}` for item-level dispositions. Its sensitive-path inventory contains paths and counts only, never values.",
            "",
        ]
    )
    return "\n".join(lines)


def prepare_output_dir(path: Path, force: bool) -> None:
    if path.is_symlink():
        raise ImportFailure(f"output directory must not be a symbolic link: {path}")
    if path.exists() and not path.is_dir():
        raise ImportFailure(f"output path exists and is not a directory: {path}")
    if path.exists():
        entries = list(path.iterdir())
        if entries and not force:
            raise ImportFailure(
                f"output directory is not empty: {path}; choose an empty directory or pass --force"
            )
        if entries and force:
            allowed_names = {"migration-report.json", "migration-review.md"}
            unexpected = [
                entry.name
                for entry in entries
                if entry.name not in allowed_names
                and not entry.name.endswith(".artemis-values.candidate.yaml")
            ]
            if unexpected:
                raise ImportFailure(
                    "--force refused to clean an output directory containing unrelated files: "
                    + ", ".join(sorted(unexpected))
                )
            for entry in entries:
                if entry.is_dir():
                    raise ImportFailure(
                        f"--force refused to remove directory from output: {entry.name}"
                    )
                entry.unlink()
    path.mkdir(parents=True, exist_ok=True)


def main() -> int:
    args = parse_args()
    validate_secret_name(args.ssl_secret_name, "--ssl-secret-name")
    validate_secret_name(args.trust_secret_name, "--trust-secret-name")
    validate_secret_name(args.jaas_secret_name, "--jaas-secret-name", jaas=True)
    document = load_json(args.input, "Chef environment")
    if not isinstance(document, dict):
        raise ImportFailure("Chef environment JSON root must be an object")
    activemq, activemq_path = discover_activemq(document, args.activemq_path)
    brokers = activemq.get("brokers")
    if not isinstance(brokers, dict) or not brokers:
        raise ImportFailure(f"{activemq_path}.brokers must be a non-empty object")
    selected_names = args.broker or sorted(brokers)
    missing_brokers = [name for name in selected_names if name not in brokers]
    if missing_brokers:
        raise ImportFailure(
            "selected broker keys were not found: " + ", ".join(sorted(missing_brokers))
        )
    if len(selected_names) != len(set(selected_names)):
        raise ImportFailure("--broker values must be unique")
    unknown_authenticated_brokers = sorted(
        set(args.authenticated_broker) - set(selected_names)
    )
    if unknown_authenticated_brokers:
        raise ImportFailure(
            "--authenticated-broker values must also be selected brokers: "
            + ", ".join(unknown_authenticated_brokers)
        )
    if len(args.authenticated_broker) != len(set(args.authenticated_broker)):
        raise ImportFailure("--authenticated-broker values must be unique")
    if args.authenticated_broker and not args.jaas_secret_name:
        raise ImportFailure("--jaas-secret-name is required with --authenticated-broker")
    if args.jaas_secret_name and not args.authenticated_broker:
        raise ImportFailure("--jaas-secret-name requires at least one --authenticated-broker")
    policy = load_policy(args.policy)
    unknown_policy_brokers = sorted(set(policy["brokers"]) - set(brokers))
    if unknown_policy_brokers:
        raise ImportFailure(
            "policy references unknown broker keys: " + ", ".join(unknown_policy_brokers)
        )
    prepare_output_dir(args.output_dir, args.force)

    source_bytes = args.input.read_bytes()
    source_sha256 = hashlib.sha256(source_bytes).hexdigest()
    environment = args.environment or str(document.get("name") or args.input.stem)
    json_report_name = "migration-report.json"
    all_items: list[dict[str, Any]] = []
    broker_summaries: dict[str, Any] = {}
    used_file_stems: set[str] = set()
    for broker_name in selected_names:
        broker = brokers[broker_name]
        if not isinstance(broker, dict):
            raise ImportFailure(f"{activemq_path}.brokers.{broker_name} must be an object")
        effective_policy = merged_policy(policy, broker_name, args.keep_role)
        candidate, broker_items = transform_broker(
            broker_name,
            broker,
            f"{activemq_path}.brokers.{broker_name}",
            effective_policy,
            args,
        )
        file_stem = unique_key(broker_name, used_file_stems)
        candidate_name = f"{file_stem}.artemis-values.candidate.yaml"
        candidate_path = args.output_dir / candidate_name
        candidate_path.write_text(candidate_yaml(candidate, json_report_name), encoding="utf-8")
        counts = Counter(entry["disposition"] for entry in broker_items)
        broker_summaries[broker_name] = {
            "candidateFile": candidate_name,
            "counts": dict(sorted(counts.items())),
        }
        all_items.extend(broker_items)

    root_known = {"brokers", "keycloak", "client", "hawtio"}
    for field in sorted(set(activemq) - root_known):
        disposition = "manual"
        reason = "unrecognized ActiveMQ environment field was not copied"
        if field in {
            "use_encrypted_v1_password",
            "use_encrypted_jmx_password",
            "enable_ssl_ui",
            "enable_ssl_jmx",
            "initial_threads",
            "limit_threads",
            "version",
        }:
            disposition = "retired"
            reason = "legacy cookbook/runtime setting is not part of the typed Artemis workload interface"
        all_items.append(item("[environment]", f"{activemq_path}.{field}", disposition, reason))
    for field, reason in (
        ("keycloak", "map current OIDC settings through the environment Keycloak values layer"),
        ("hawtio", "map current console ingress and redirect settings through the environment layer"),
        ("client", "legacy cookbook client selector is not an Artemis workload value"),
    ):
        if field in activemq:
            all_items.append(item("[environment]", f"{activemq_path}.{field}", "manual", reason))

    secret_paths = sensitive_paths(document)
    report: dict[str, Any] = {
        "schemaVersion": SCHEMA_VERSION,
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "environment": environment,
        "sourceFile": args.input.name,
        "sourceSha256": source_sha256,
        "activemqPath": activemq_path,
        "status": "REVIEW_REQUIRED",
        "secretValuesEmitted": False,
        "sensitiveSourceInventory": {
            "count": len(secret_paths),
            "paths": secret_paths,
        },
        "policy": {
            "file": args.policy.name if args.policy else None,
            "schemaVersion": POLICY_SCHEMA_VERSION,
            "defaultDroppedRoles": sorted(
                set(policy["defaults"].get("dropRoles", [])) - set(args.keep_role)
            ),
            "includeDlqDestinations": policy["defaults"].get(
                "includeDlqDestinations", False
            ),
        },
        "brokers": broker_summaries,
        "jsonReportFile": json_report_name,
        "items": all_items,
    }
    (args.output_dir / json_report_name).write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (args.output_dir / "migration-review.md").write_text(
        markdown_report(report), encoding="utf-8"
    )
    print(
        f"Chef ActiveMQ import: REVIEW_REQUIRED ({len(selected_names)} broker candidate(s), "
        f"{len(all_items)} disposition item(s)); output: {args.output_dir}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ImportFailure as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2)
