apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: messaging-platform
  namespace: PLACEHOLDER_ARGOCD_NAMESPACE
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  description: Generic Artemis platform resources for three EKS clusters
  sourceRepos:
    - https://example.invalid/PLACEHOLDER_ORG/PLACEHOLDER_GITOPS_REPOSITORY.git
    - PLACEHOLDER_ECR_REGISTRY
  destinations:
    - namespace: PLACEHOLDER_PLATFORM_NAMESPACE
      server: https://PLACEHOLDER_TEST_EKS_API_SERVER
    - namespace: PLACEHOLDER_TEST_NAMESPACE_*
      server: https://PLACEHOLDER_TEST_EKS_API_SERVER
    - namespace: PLACEHOLDER_PLATFORM_NAMESPACE
      server: https://PLACEHOLDER_NONPROD_EKS_API_SERVER
    - namespace: PLACEHOLDER_NONPROD_NAMESPACE_*
      server: https://PLACEHOLDER_NONPROD_EKS_API_SERVER
    - namespace: PLACEHOLDER_PLATFORM_NAMESPACE
      server: https://PLACEHOLDER_PROD_EKS_API_SERVER
    - namespace: PLACEHOLDER_PROD_NAMESPACE_*
      server: https://PLACEHOLDER_PROD_EKS_API_SERVER
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
