{{- if .Values.security.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "artemis-ha.serviceAccountName" . }}
  labels:
    {{- include "artemis-ha.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.security.serviceAccount.automountServiceAccountToken }}
{{- end }}
