apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.headlessServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
    zookeeper.example.io/service: headless
  annotations:
    {{- with .Values.service.headless.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: {{ .Values.service.client.port }}
      targetPort: client
      protocol: TCP
    {{- if .Values.tls.client.enabled }}
    - name: client-tls
      port: {{ .Values.tls.client.port }}
      targetPort: client-tls
      protocol: TCP
    {{- end }}
    - name: quorum
      port: 2888
      targetPort: quorum
      protocol: TCP
    - name: leader-election
      port: 3888
      targetPort: leader-election
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.clientServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
    zookeeper.example.io/service: client
  {{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    prometheus.io/path: /metrics
  {{- end }}
spec:
  type: {{ .Values.service.client.type }}
  ports:
    - name: client
      port: {{ .Values.service.client.port }}
      targetPort: client
      protocol: TCP
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
