apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-controller-manager-v2
spec:
  template:
    spec:
      containers:
        - name: manager
          image: PLACEHOLDER_PROD_ECR_REPOSITORY/arkmq-operator:2.2.0@sha256:ab922b10ed90483cd4ec67d978d618b743b62ef5daba6fe97c7e10a72936302f
          env:
            - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2530
              value: PLACEHOLDER_PROD_ECR_REPOSITORY/activemq-artemis-broker-init:artemis.2.53.0@sha256:0000000000000000000000000000000000000000000000000000000000000000
            - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2530
              value: PLACEHOLDER_PROD_ECR_REPOSITORY/activemq-artemis-broker-kubernetes:artemis.2.53.0@sha256:0000000000000000000000000000000000000000000000000000000000000000
