apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: activemq-artemis-controller-manager-v2
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: activemq-artemis-operator
